version: 2.1

jobs:
  print_hello:
    docker:
      - image: cimg/node:17.7.2
    steps:
      - run: echo "hello"
  print_world:
    docker:
      - image: cimg/node:17.7.2
    steps:
      - run: echo "world"

workflows:
  print_hello_world:
    jobs:
      - print_hello
      - print_world:
          requires:
          - print_hello
